//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApp.Hotel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vendor", Namespace="http://schemas.datacontract.org/2004/07/HotelService.Contract")]
    [System.SerializableAttribute()]
    public partial class Vendor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime join_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime join_date {
            get {
                return this.join_dateField;
            }
            set {
                if ((this.join_dateField.Equals(value) != true)) {
                    this.join_dateField = value;
                    this.RaisePropertyChanged("join_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_address {
            get {
                return this.vendor_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_addressField, value) != true)) {
                    this.vendor_addressField = value;
                    this.RaisePropertyChanged("vendor_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_company {
            get {
                return this.vendor_companyField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_companyField, value) != true)) {
                    this.vendor_companyField = value;
                    this.RaisePropertyChanged("vendor_company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_name {
            get {
                return this.vendor_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_nameField, value) != true)) {
                    this.vendor_nameField = value;
                    this.RaisePropertyChanged("vendor_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_phone {
            get {
                return this.vendor_phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_phoneField, value) != true)) {
                    this.vendor_phoneField = value;
                    this.RaisePropertyChanged("vendor_phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemCategory", Namespace="http://schemas.datacontract.org/2004/07/HotelService.Contract")]
    [System.SerializableAttribute()]
    public partial class ItemCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebApp.Hotel.Item ItemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelWebApp.Hotel.Item Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_code {
            get {
                return this.category_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.category_codeField, value) != true)) {
                    this.category_codeField = value;
                    this.RaisePropertyChanged("category_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string category_name {
            get {
                return this.category_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.category_nameField, value) != true)) {
                    this.category_nameField = value;
                    this.RaisePropertyChanged("category_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/HotelService.Contract")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebApp.Hotel.ItemCategory ItemCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HotelWebApp.Hotel.Vendor VendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> added_by_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> create_by_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> edit_by_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal item_prizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelWebApp.Hotel.ItemCategory ItemCategory {
            get {
                return this.ItemCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemCategoryField, value) != true)) {
                    this.ItemCategoryField = value;
                    this.RaisePropertyChanged("ItemCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HotelWebApp.Hotel.Vendor Vendor {
            get {
                return this.VendorField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorField, value) != true)) {
                    this.VendorField = value;
                    this.RaisePropertyChanged("Vendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> added_by_date {
            get {
                return this.added_by_dateField;
            }
            set {
                if ((this.added_by_dateField.Equals(value) != true)) {
                    this.added_by_dateField = value;
                    this.RaisePropertyChanged("added_by_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> create_by_date {
            get {
                return this.create_by_dateField;
            }
            set {
                if ((this.create_by_dateField.Equals(value) != true)) {
                    this.create_by_dateField = value;
                    this.RaisePropertyChanged("create_by_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> edit_by_date {
            get {
                return this.edit_by_dateField;
            }
            set {
                if ((this.edit_by_dateField.Equals(value) != true)) {
                    this.edit_by_dateField = value;
                    this.RaisePropertyChanged("edit_by_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_code {
            get {
                return this.item_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.item_codeField, value) != true)) {
                    this.item_codeField = value;
                    this.RaisePropertyChanged("item_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string item_name {
            get {
                return this.item_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.item_nameField, value) != true)) {
                    this.item_nameField = value;
                    this.RaisePropertyChanged("item_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal item_prize {
            get {
                return this.item_prizeField;
            }
            set {
                if ((this.item_prizeField.Equals(value) != true)) {
                    this.item_prizeField = value;
                    this.RaisePropertyChanged("item_prize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hotel.IHotel")]
    public interface IHotel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/FindVendors", ReplyAction="http://tempuri.org/IHotel/FindVendorsResponse")]
        HotelWebApp.Hotel.Vendor[] FindVendors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/FindVendors", ReplyAction="http://tempuri.org/IHotel/FindVendorsResponse")]
        System.Threading.Tasks.Task<HotelWebApp.Hotel.Vendor[]> FindVendorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/FindCategory", ReplyAction="http://tempuri.org/IHotel/FindCategoryResponse")]
        HotelWebApp.Hotel.ItemCategory[] FindCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/FindCategory", ReplyAction="http://tempuri.org/IHotel/FindCategoryResponse")]
        System.Threading.Tasks.Task<HotelWebApp.Hotel.ItemCategory[]> FindCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/FindItemCategory", ReplyAction="http://tempuri.org/IHotel/FindItemCategoryResponse")]
        HotelWebApp.Hotel.ItemCategory[] FindItemCategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/FindItemCategory", ReplyAction="http://tempuri.org/IHotel/FindItemCategoryResponse")]
        System.Threading.Tasks.Task<HotelWebApp.Hotel.ItemCategory[]> FindItemCategoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/SelectAllItems", ReplyAction="http://tempuri.org/IHotel/SelectAllItemsResponse")]
        HotelWebApp.Hotel.Item[] SelectAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/SelectAllItems", ReplyAction="http://tempuri.org/IHotel/SelectAllItemsResponse")]
        System.Threading.Tasks.Task<HotelWebApp.Hotel.Item[]> SelectAllItemsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelChannel : HotelWebApp.Hotel.IHotel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelClient : System.ServiceModel.ClientBase<HotelWebApp.Hotel.IHotel>, HotelWebApp.Hotel.IHotel {
        
        public HotelClient() {
        }
        
        public HotelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelWebApp.Hotel.Vendor[] FindVendors() {
            return base.Channel.FindVendors();
        }
        
        public System.Threading.Tasks.Task<HotelWebApp.Hotel.Vendor[]> FindVendorsAsync() {
            return base.Channel.FindVendorsAsync();
        }
        
        public HotelWebApp.Hotel.ItemCategory[] FindCategory() {
            return base.Channel.FindCategory();
        }
        
        public System.Threading.Tasks.Task<HotelWebApp.Hotel.ItemCategory[]> FindCategoryAsync() {
            return base.Channel.FindCategoryAsync();
        }
        
        public HotelWebApp.Hotel.ItemCategory[] FindItemCategory() {
            return base.Channel.FindItemCategory();
        }
        
        public System.Threading.Tasks.Task<HotelWebApp.Hotel.ItemCategory[]> FindItemCategoryAsync() {
            return base.Channel.FindItemCategoryAsync();
        }
        
        public HotelWebApp.Hotel.Item[] SelectAllItems() {
            return base.Channel.SelectAllItems();
        }
        
        public System.Threading.Tasks.Task<HotelWebApp.Hotel.Item[]> SelectAllItemsAsync() {
            return base.Channel.SelectAllItemsAsync();
        }
    }
}
