//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApp.HotelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vendor", Namespace="http://schemas.datacontract.org/2004/07/HotelService.Contract")]
    [System.SerializableAttribute()]
    public partial class Vendor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime join_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_companyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendor_phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime join_date {
            get {
                return this.join_dateField;
            }
            set {
                if ((this.join_dateField.Equals(value) != true)) {
                    this.join_dateField = value;
                    this.RaisePropertyChanged("join_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_address {
            get {
                return this.vendor_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_addressField, value) != true)) {
                    this.vendor_addressField = value;
                    this.RaisePropertyChanged("vendor_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_company {
            get {
                return this.vendor_companyField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_companyField, value) != true)) {
                    this.vendor_companyField = value;
                    this.RaisePropertyChanged("vendor_company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_name {
            get {
                return this.vendor_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_nameField, value) != true)) {
                    this.vendor_nameField = value;
                    this.RaisePropertyChanged("vendor_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor_phone {
            get {
                return this.vendor_phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.vendor_phoneField, value) != true)) {
                    this.vendor_phoneField = value;
                    this.RaisePropertyChanged("vendor_phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelService.IHotel")]
    public interface IHotel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/findByID", ReplyAction="http://tempuri.org/IHotel/findByIDResponse")]
        HotelWebApp.HotelService.Vendor[] findByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/findByID", ReplyAction="http://tempuri.org/IHotel/findByIDResponse")]
        System.Threading.Tasks.Task<HotelWebApp.HotelService.Vendor[]> findByIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelChannel : HotelWebApp.HotelService.IHotel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelClient : System.ServiceModel.ClientBase<HotelWebApp.HotelService.IHotel>, HotelWebApp.HotelService.IHotel {
        
        public HotelClient() {
        }
        
        public HotelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelWebApp.HotelService.Vendor[] findByID(int id) {
            return base.Channel.findByID(id);
        }
        
        public System.Threading.Tasks.Task<HotelWebApp.HotelService.Vendor[]> findByIDAsync(int id) {
            return base.Channel.findByIDAsync(id);
        }
    }
}
